apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset-app
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - app: nginx
        ns: nginx-ns
        url: https://kubernetes.default.svc
      - app: redis-cluster
        ns: redis-ns
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{app}}-test'
    spec:
      project: "default"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        helm:
          valueFiles:
            - values.yaml
      source:
        repoURL: https://github.com/bekzatbaubek/argocd-apps.git
        targetRevision: main
        path: apps/{{app}}
      destination:
        server: '{{url}}'
        namespace: '{{ns}}'