apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-bootstrap
spec:
  generators:
    - matrix:
      generators:
        - list:
            elements:
            - cluster: test-ue-1
              url: https://kubernetes.default.svc
            - cluster: test-ue-2
              url: https://kubernetes.default.svc
        - git:
            repoURL: https://github.com/bekzatbaubek/argocd-apps.git
            revision: HEAD
            directories:
            - path: apps/*/*
  template:
    metadata:
      name: '{{path.basename}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/bekzatbaubek/argocd-apps.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
          - values.yaml
          - 'values-{{cluster}}.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true