apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-bootstrap
spec:
  generators:
  - git:
      repoURL: https://github.com/bekzatbaubek/argocd-apps.git
      revision: HEAD
      directories:
      - path: apps/**
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/bekzatbaubek/argocd-apps.git
        targetRevision: HEAD
        path: 'apps/{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'