apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset-app
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - app: nginx
        ns: nginx-ns
        url: https://kubernetes.default.svc
      - app: prometheus
        ns: prometheus-ns
        url: https://kubernetes.default.svc
      - app: test-app
        ns: example-app-ns
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{app}}-test'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/bekzatbaubek/argocd-apps.git
        targetRevision: main
        path: apps/{{app}}
        helm:
          valueFiles:
          - values.yaml
      destination:
        server: '{{url}}'
        namespace: '{{ns}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true