apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset-app
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - app: nginx
        ns: nginx-ns
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-test'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/bekzatbaubek/argocd-apps.git
        targetRevision: main
        path: apps/{{app}}
      destination:
        server: '{{url}}'
        namespace: '{{ns}}'