apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-bootstrap
spec:
  generators:
  - git:
      repoURL: https://github.com/bekzatbaubek/argocd-apps.git
      revision: HEAD
      directories:
      - path: apps/*/*
  template:
    metadata:
      name: '{{path.basename}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/bekzatbaubek/argocd-apps.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          # Helm values files for overriding values in the helm chart
          # The path is relative to the spec.source.path directory defined above
          valueFiles:
          - values.yaml
        # Ignore locally missing valueFiles when installing Helm chart. Defaults to false
        ignoreMissingValueFiles: false

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true