apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset-app
  namespace: argocd
spec:
  generators:
    - git:
      repoURL: https://github.com/bekzatbaubek/argocd-apps.git
      revision: HEAD
      directories:
      - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: "default"
      source:
        repoURL: https://github.com/bekzatbaubek/argocd-apps.git
        targetRevision: main
        path: '{{path.basename}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[0]}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true